Uncomment the setDefaultValue method, which is required by some plugins. They are normally built when gsl is installed :-)
I got the following compilation error:
compiling /home/franz/brisset/linux/SRC_ARCHIVE/SVN/kst2/src/plugins/filters/despike/filterdespike.cpp             
/home/franz/brisset/linux/SRC_ARCHIVE/SVN/kst2/src/plugins/filters/despike/filterdespike.cpp: In member function ‘virtual void ConfigWidgetFilterDespikePlugin::setObjectStore(Kst::ObjectStore*)’:                                                                                                                                                                   
/home/franz/brisset/linux/SRC_ARCHIVE/SVN/kst2/src/plugins/filters/despike/filterdespike.cpp:35: error: ‘class Kst::ScalarSelector’ has no member named ‘setDefaultValue’          
/home/franz/brisset/linux/SRC_ARCHIVE/SVN/kst2/src/plugins/filters/despike/filterdespike.cpp:36: error: ‘class Kst::ScalarSelector’ has no member named ‘setDefaultValue’          
make[3]: *** [tmp/filterdespike.o] Fehler 1                                                                                                                                        

Barth, from the log message in commit #1062814 I have the feeling this was actually more a "this should not be needed" kind of cleanup, but apparently this method can't be removed just like that.



git-svn-id: svn+ssh://svn.kde.org/home/kde/branches/work/kst/portto4/kst@1062817 283d02a7-25f6-0310-bc7c-ecb5cbfe19da